title: MIT Libraries TIMDEX API Documentation
description: TIMDEX API Documentation

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc2
plugins:
  - "jekyll-remote-theme"
  - "jekyll-seo-tag"
color_scheme: dark
aux_links:
  "Timdex":
    - "//timdex.mit.edu"

exclude:
  - architecture-decisions
