title: MIT Libraries TIMDEX API Documentation
description: TIMDEX API Documentation

remote_theme: JPrevost/just-the-docs@skip_main_rebased
plugins:
  - "jekyll-remote-theme"
  - "jekyll-seo-tag"
color_scheme: dark
aux_links:
  "Timdex":
    - "//timdex.mit.edu"

exclude:
  - architecture-decisions
