title: MIT Libraries TIMDEX API Documentation
description: TIMDEX API Documentation

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
plugins:
  - "jekyll-remote-theme"
  - "jekyll-seo-tag"
color_scheme: dark
aux_links:
  "Timdex":
    - "//timdex.mit.edu"

exclude:
  - architecture-decisions

nav_external_links:
  - title: Reference Docs
    url: ./reference
    hide_icon: false # set to true to hide the external link icon - defaults to false

mermaid:
  version: "9.1.7"
